version: "3"

services:
  db:
    image: postgres:11
    restart: always
    ports:
      - "5466:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: go-template
      POSTGRES_DB: go-template-db
  go-template:
    restart: always
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://go-template:password@db:5466/go-template-db?schema=public
      APP_PORT: 3000
